tap "adoptopenjdk/openjdk"
tap "aws/tap"
tap "benbjohnson/litestream"
tap "borkdude/brew"
tap "buo/cask-upgrade"
tap "gcenx/apple"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
brew "sqlite"
brew "cheat"
brew "cmake"
brew "coreutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "gnu-sed"
brew "gnupg"
brew "htop"
brew "jq"
brew "libpq", link: true
brew "maven"
brew "neofetch"
brew "neovim"
brew "openjdk@17"
brew "osx-cpu-temp"
brew "python@3"
brew "reattach-to-user-namespace"
brew "redis"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tmuxinator"
brew "universal-ctags", args: ["HEAD"]
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "alt-tab"
cask "dbeaver-community"
cask "docker"
cask "figma"
cask "font-meslo-lg-nerd-font"
cask "hammerspoon"
cask "handbrake"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keycastr"
cask "microsoft-edge"
cask "ngrok"
cask "obs"
cask "postman"
cask "rectangle"
cask "redis-pro"
cask "sublime-text"
cask "vimr"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Color Picker Plus", id: 1499052260
mas "Developer", id: 640199958
mas "Focus To-Do", id: 1258530160
mas "HEIC image batch converter", id: 1566575751
mas "Keynote", id: 409183694
mas "Microsoft Word", id: 462054704
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
mas "Screen Cursor", id: 1577211880
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
mas "무비스트", id: 461788075
mas "반디집", id: 1265704574
mas "카카오톡", id: 869223134
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "alexcvzz.vscode-sqlite"
vscode "andys8.jest-snippets"
vscode "blaugold.melos-code"
vscode "blaxou.freezed"
vscode "bradlc.vscode-tailwindcss"
vscode "bruno-api-client.bruno"
vscode "codezombiech.gitignore"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "dkundel.vscode-new-file"
vscode "donjayamanne.python-environment-manager"
vscode "editorconfig.editorconfig"
vscode "equinusocio.vsc-community-material-theme"
vscode "esbenp.prettier-vscode"
vscode "figma.figma-vscode-extension"
vscode "george-alisson.html-preview-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "hirantha.json-to-dart"
vscode "jakebecker.elixir-ls"
vscode "jsayol.firebase-explorer"
vscode "mariusalchimavicius.json-to-ts"
vscode "mohsen1.prettify-json"
vscode "mquandalle.graphql"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ko"
vscode "ms-playwright.playwright"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.js-debug-nightly"
vscode "ms-vscode.live-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "nash.awesome-flutter-snippets"
vscode "orta.vscode-jest"
vscode "phoenixframework.phoenix"
vscode "pkief.material-icon-theme"
vscode "prisma.prisma"
vscode "redhat.fabric8-analytics"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ritvyk.heex-html"
vscode "svelte.svelte-vscode"
vscode "tal7aouy.theme"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
